# Generated by Django 4.1.3 on 2022-12-04 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(default=123, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(3)])),
                ('number', models.PositiveIntegerField(default=1234567890123456, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(16)])),
                ('card_released', models.DateField()),
                ('valid_date', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
