# Generated by Django 4.1.3 on 2022-12-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_count', models.IntegerField()),
                ('card_series', models.CharField(max_length=3)),
                ('card_number', models.CharField(max_length=16)),
                ('card_released', models.DateTimeField(auto_now_add=True, verbose_name='date released')),
                ('card_valid_date', models.DateTimeField()),
                ('card_use_date', models.DateTimeField()),
                ('card_balance', models.IntegerField()),
                ('card_status', models.BooleanField()),
            ],
        ),
    ]
