# Generated by Django 4.1.3 on 2022-12-04 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.PositiveIntegerField(default=1234567890123456, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(17)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.PositiveIntegerField(default=123, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
