# Generated by Django 4.1.3 on 2022-12-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_released',
            field=models.DateTimeField(),
        ),
    ]
