# Generated by Django 4.1.3 on 2022-12-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0002_alter_card_number_alter_card_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.CharField(max_length=3),
        ),
    ]
